INDEX_PATH = "portfolio-db"
DATABASE_PATH = "data/portfolio-knowledge.json"

DEFAULT_MODEL = "qwen/qwen3-32b"
DEFAULT_TEMPERATURE = 0.7
RETRIEVAL_K = 2
STREAM_DELAY = 0.01

WEB_SEARCH_MAX_RESULTS = 4
WEB_SEARCH_CONTENT_MAX_LENGTH = 300

